### ISSUE TITLE
Replace tag

### ISSUE THREAD

**Issue by tranmanhhung** [dcollien/FilterHTML#17]
I want replace tag
eg:
'span class=\"italic\"': 'em',
'span class=\"bold\"': 'strong',

**Comment by dcollien** [comment]
This level of customisation is pushing the scope of this project as a lightweight HTML filter - you might be better off using [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) to do this conversion, and then run the resulting HTML through this filter for sanitisation

**Comment by tranmanhhung** [comment]
I used BeautifulSoup for this issue to success. Thank you.
