### ISSUE TITLE
Tree whitelist

### ISSUE THREAD

**Issue by Garito** [dcollien/FilterHTML#6]
Hi!
I'm wondering if I can define a tree shape whitelist
Meaning that for instance I don't want to allow span's if they are alone but yes if they are inside a div

Is it possible?

Thanks!!!!

**Comment by dcollien** [comment]
I'll have a look into it!

**Comment by Garito** [comment]
Nice, thanks!

**Comment by dcollien** [comment]
Hi @Garito,

It's taken me a while to get around to it, but I've added in some functionality which may do what you were looking for.

You can now use functions to specify the whitelist for a tag. These functions take the current stack of tags as an argument, so you can see if the tag that's being operated on is inside another tag.
These functions can return a dictionary-like object as the whitelist specification to use, or None/null if you want the tag to be removed, or False/false if you want to remove the tag and its contents.

Here's an example in Python:
https://github.com/dcollien/FilterHTML/blob/master/tests/run_tests.py#L531
(test_spec_delegate)
