### ISSUE TITLE
Whitelisting/Restricting data-attributes

### ISSUE THREAD

**Issue by Merenon** [dcollien/FilterHTML#7]
Unfortunately, I couldn't find a way to create a whitelist spec which allows/restricts any kind of data-attributes - or more general: a way to use regex pattern for attribute names.

Is there a way to filter for data-attributes I missed?
If not, this would be an important feature request.

**Comment by Merenon** [comment]
I digged into the code and made some changes myself.
I would appreciate if you might have a look at it:
https://github.com/dcollien/FilterHTML/pull/8

**Comment by dcollien** [comment]
Updated to support this in 0.6
